apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikudepotserver-pg
  template:
    metadata:
      labels:
        app: haikudepotserver-pg
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: haikudepotserver-pg-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: haikudepotserver-pg-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver-pg-svc
  labels:
    app: haikudepotserver-pg
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: haikudepotserver-pg