apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /mnt/k8s-kind-cluster
        containerPath: /data
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8089
        protocol: TCP